# Generated by Django 6.1 on 2026-08-16 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0007_articletask_listeningtask_passagetask_podcasttask_and_more'),
        ('listening', '0002_listening_created_by_listening_updated_at'),
        ('reading', '0004_rename_image_readingarticle_cover'),
        ('videos', '0002_alter_listeningpodcast_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress', to='assignments.assignment')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'assignment')},
            },
        ),
        migrations.CreateModel(
            name='ProgressReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.readingpassage')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='progress.studentprogress')),
            ],
            options={
                'unique_together': {('progress', 'passage')},
            },
        ),
        migrations.CreateModel(
            name='ProgressPodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.listeningpodcast')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_progress', to='progress.studentprogress')),
            ],
            options={
                'unique_together': {('progress', 'podcast')},
            },
        ),
        migrations.CreateModel(
            name='ProgressListening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listening_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.listening')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_progress', to='progress.studentprogress')),
            ],
            options={
                'unique_together': {('progress', 'listening_test')},
            },
        ),
        migrations.CreateModel(
            name='ProgressArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.readingarticle')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_progress', to='progress.studentprogress')),
            ],
            options={
                'unique_together': {('progress', 'article')},
            },
        ),
    ]
