# Generated by Django 6.1 on 2026-08-21 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_remove_assignment_group_assignment_groups_and_more'),
        ('groups', '0002_alter_group_id'),
        ('progress', '0002_studentprogress_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('user', 'group', 'assignment')},
        ),
    ]
