# Generated by Django 6.1 on 2026-08-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_remove_assignment_due_date_remove_assignment_groups_and_more'),
        ('progress', '0003_alter_studentprogress_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogress',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress', to='assignments.assignmentdistribution'),
        ),
    ]
