# Generated by Django 6.1 on 2026-08-26 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_remove_assignment_due_date_remove_assignment_groups_and_more'),
        ('groups', '0002_alter_group_id'),
        ('progress', '0004_alter_studentprogress_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogress',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_progress', to='assignments.assignmentdistribution'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_groups', to='groups.group'),
        ),
    ]
