# Generated by Django 6.1 on 2026-08-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_alter_studentprogress_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreading',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
