# Generated by Django 6.1 on 2026-08-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('part', models.CharField(choices=[('Part 1', 'Part 1'), ('Part 2', 'Part 2'), ('Part 3', 'Part 3'), ('Part 4', 'Part 4')], default='Part 1', max_length=6)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('audio_file', models.FileField(upload_to='listening/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('image_file', models.ImageField(upload_to='listening/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listening.listening')),
            ],
        ),
    ]
