# Generated by Django 6.1 on 2026-08-07 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listening',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listening',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
