# Generated by Django 6.1 on 2026-08-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignmenttask_assignmentitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmenttask',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='assignmenttask',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmenttask',
            name='student',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='AssignmentItem',
        ),
        migrations.DeleteModel(
            name='AssignmentTask',
        ),
    ]
