# Generated by Django 6.1 on 2026-08-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignmenttask_unique_together_and_more'),
        ('listening', '0002_listening_created_by_listening_updated_at'),
        ('reading', '0003_readingpassage_passage'),
        ('videos', '0002_alter_listeningpodcast_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reading.readingarticle'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='listening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='listening.listening'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reading_passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reading.readingpassage'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='videos.listeningpodcast'),
        ),
    ]
