# Generated by Django 6.1 on 2026-08-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_article_assignment_listening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='listening',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='reading_passage',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='video',
        ),
        migrations.CreateModel(
            name='AssignmentTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('READING_ARTICLE', 'Reading Article'), ('READING_PASSAGE', 'Reading Passage'), ('LISTENING', 'Listening'), ('VIDEO', 'Video')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Assignment Task',
                'verbose_name_plural': 'Assignment Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
