# Generated by Django 6.1 on 2026-08-08 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_assignment_article_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttasks',
            name='task_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Obekt ID raqami'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmenttasks',
            name='task_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'reading'), ('model__in', ['readingarticle', 'readingpassage'])), models.Q(('app_label', 'listening'), ('model', 'listening')), models.Q(('app_label', 'videos'), ('model', 'listeningpodcast')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Vazifa turi'),
        ),
    ]
