# Generated by Django 6.1 on 2026-08-08 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignmenttasks_task_id_and_more'),
        ('listening', '0002_listening_created_by_listening_updated_at'),
        ('reading', '0003_readingpassage_passage'),
        ('videos', '0002_alter_listeningpodcast_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tasks', to='assignments.assignment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tasks', to='reading.readingarticle')),
            ],
            options={
                'verbose_name': 'Assignment Task',
                'verbose_name_plural': 'Assignment Tasks',
            },
        ),
        migrations.CreateModel(
            name='ListeningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_tasks', to='assignments.assignment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_tasks', to='listening.listening')),
            ],
            options={
                'verbose_name': 'Assignment Task',
                'verbose_name_plural': 'Assignment Tasks',
            },
        ),
        migrations.CreateModel(
            name='PassageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_tasks', to='assignments.assignment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_tasks', to='reading.readingpassage')),
            ],
            options={
                'verbose_name': 'Assignment Task',
                'verbose_name_plural': 'Assignment Tasks',
            },
        ),
        migrations.CreateModel(
            name='PodcastTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_tasks', to='assignments.assignment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_tasks', to='videos.listeningpodcast')),
            ],
            options={
                'verbose_name': 'Assignment Task',
                'verbose_name_plural': 'Assignment Tasks',
            },
        ),
        migrations.DeleteModel(
            name='AssignmentTasks',
        ),
    ]
