# Generated by Django 6.1 on 2026-08-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_articletask_listeningtask_passagetask_podcasttask_and_more'),
        ('groups', '0002_alter_group_id'),
        ('listening', '0002_listening_created_by_listening_updated_at'),
        ('reading', '0004_rename_image_readingarticle_cover'),
        ('videos', '0002_alter_listeningpodcast_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='group',
        ),
        migrations.AddField(
            model_name='assignment',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='groups.group'),
        ),
        migrations.AlterUniqueTogether(
            name='articletask',
            unique_together={('assignment', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='listeningtask',
            unique_together={('assignment', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='passagetask',
            unique_together={('assignment', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='podcasttask',
            unique_together={('assignment', 'task')},
        ),
    ]
