# Generated by Django 6.1 on 2026-08-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_remove_assignment_group_assignment_groups_and_more'),
        ('groups', '0002_alter_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='groups',
        ),
        migrations.CreateModel(
            name='AssignmentDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='assignments.assignment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_distributions', to='groups.group')),
            ],
            options={
                'verbose_name': 'Assignment Distribution',
                'verbose_name_plural': 'Assignment Distributions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'group'), name='unique_assignment_group_distribution')],
            },
        ),
    ]
