# Generated by Django 6.1 on 2026-08-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_readingarticle_subtitle_readingpassage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpassage',
            name='passage',
            field=models.CharField(choices=[('Passage 1', 'Passage 1'), ('Passage 2', 'Passage 2'), ('Passage 3', 'Passage 3')], default='Passage 1', max_length=50),
        ),
    ]
