# Generated by Django 6.1 on 2026-08-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_readingpassage_passage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingarticle',
            old_name='image',
            new_name='cover',
        ),
    ]
